### ISSUE TITLE
Move admin tool into Prime Launch

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#147]
See spec:  https://www.notion.so/curvelabs/339a249185e14ddcbd731e5ba07c46c7?v=a921af62e868495db519e62d491d48c2&p=3707a3825fa6401a84cf49c7024ed7b3
Doug has created some skeleton code to get Mihir started.

**Comment by dkent600** [comment]
Closing as has been duplicated by:  https://github.com/PrimeDAO/prime-launch-dapp/issues/187
