### ISSUE TITLE
Create and use PrimeDAO token lists

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#149]
Kolektivo is tasked with coming up with token lists.  I'm not yet sure what lists we need.  Possibly a list of project tokens based on submissions of launches?  This list would fully specify each token (symbol, icon, etc).

We certainly need a list of selectable funding tokens for the dropdown requested in this card:  @(Moved to Zenhub)Seed Wizard: Funding Tokens.  This can simply be a list of token addresses.

![(9) Create and u](https://user-images.githubusercontent.com/24368665/131127394-6f607896-e0c7-47f8-ad2e-814b960a4681.png)

**Comment by renc-curvelabs** [comment]
Deadline for Kolektivo to provide token list: 10.09.2021

**Comment by fabianschu** [comment]
Luuk asked me to create three lists based on the three tabs in [this](https://docs.google.com/spreadsheets/d/14agNdsRvvPJec56iYEgyiz7gPJdvNUXjAIucKaI5Bek/edit#gid=0) google sheet:
- payment tokens: can be used for the Seed wizard 
- certified (B+ or higher) & quality tokens (A+):  are for Indices and Prime Rating

For the token lists to be listed on [tokenlists](www.tokenlists.org), it is necessary to create an issue in [this](https://github.com/Uniswap/tokenlists-org/issues) repo. Before this can be done, the lists need to be hosted somewhere. For that I wanted to follow the recommendation as as stated [here](https://github.com/Uniswap/token-lists#deploying-your-list). To be able to do so one obvious solution would be to create three subdomains for `primexyz.eth`. Then we could host the three JSON files on IPFS via pinata and associate their content hashes with the three subdomains. Then I could create the issue in the uniswap/tokenlists repo.
@dkent600 @renc-curvelabs

**Comment by fabianschu** [comment]
If we follow this approach, what is left to do is:
- validate the schema correctness of the three json files that I created
- upload the json files via pinata
- provide the three content hashes to Luuk
- create three subdomains (task for Luuk)
- associate the three new subdomains with the three content hashes (task for Luuk)
- create an issue in the uniswap/tokenlists repo

**Comment by fabianschu** [comment]
If ever a list needed to be modified, we would need to upload a new list and associate the respective ENS subdomain with the new content hash.

**Comment by dkent600** [comment]
We have decided to host the files in a public git repo under primedao.  No ENS nor IPFS

**Comment by fabianschu** [comment]
This is been moved to the new repository `tokenlists`. Issue to be found [here](https://github.com/PrimeDAO/tokenlists/issues/2).
