### ISSUE TITLE
Remove uses of rem and em from the wizard

### ISSUE THREAD

**Issue by Zitzak** [PrimeDAO/prime-launch-dapp#170]
We have wanted to remove uses of rem and em from our css.  These create unexpected consequences with managing layout and require additional work to compare and sync with the wireframes which are entirely given in px.

However, the css in the new seed wizard is still replete with uses of REM and EM.  Please convert these to the PX values that are given in the wireframes.  Be sure to thoroughly test both desktop and mobile layouts.
### Screenshot of conversation in Notion
![Screen Shot 2021-08-27 at 18.18.15.png](https://images.zenhubusercontent.com/610113350e9daa1716323d68/4b6a9b0a-2b47-4c78-b804-458057b838b8)

**Comment by renc-curvelabs** [comment]
@dkent600 Can you let me know if this is still relevant?
