### ISSUE TITLE
Cannot Confirm deploySeed on Gnosis(Rinkeby)

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#195]
I am trying to create a new seed against Rinkeby. I cannot confirm the latest seed on Gnosis. https://rinkeby.gnosis-safe.io/app/#/safes/0x2E46E481d57477A0663a7Ec61E7eDc65F4cb7F5C/transactions

Here's the error message:

Confirmation transaction failed - Transaction has been reverted by the EVM: { "blockHash": "0x65369337553fe07b4dbd067e12b44ecfadbb87e978162d3b4e697671540c5aa6", "blockNumber": 9284646, "contractAddress": null, "cumulativeGasUsed": 45277, "effectiveGasPrice": "0xd09dc3000", "from": "0x8625f29e4d06d0a3998ed8c9e45f4b04c7b28d00", "gasUsed": 45277, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x2e46e481d57477a0663a7ec61e7edc65f4cb7f5c", "transactionHash": "0x69a97aeb91c5da725dd96c96e4ffe98250834628f02fd4be92c472a4f888e030", "transactionIndex": 0, "type": "0x2", "events": {} }

**Comment by codebuster22** [comment]
The transaction was blocked by transactions with a lower nonce. Gnosis expects us to execute transactions in sequence.
