### ISSUE TITLE
Set up a call with PERP

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#198]

**Comment by dkent600** [comment]
@BartuCulha What is the reason for this and the status?  My understanding is that PERP might provide information and reusable code for developing the LBP graphs that we want to use in the LBP dashboard and optionally in the stage4 wizard.  If so, we will want this sooner than later.

**Comment by BartuCulha** [comment]
PERP told Luuk to check out https://copperlaunch.com/.

Luuk posted an image of how PERP is doing the graphs and he said he will provide a light + dark version of the graphs. Here's the image he has provided.
![image_2021-09-14_10-31-46](https://user-images.githubusercontent.com/24368665/133806777-38cbfafb-53c7-482a-adf2-2cdcad5428c1.png)

**Comment by dkent600** [comment]
What we’re hoping for more than anything is their source code (a Git repo)

**Comment by BartuCulha** [comment]
I added it as an action item. I'll ask Luuk
