### ISSUE TITLE
Create UI for Admin Panel LBP

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#208]
@BartuCulha This is being worked here:  https://github.com/PrimeDAO/prime-launch-dapp/issues/187

Ideal User Flow:-
1. Admin comes to Prime Launch
2. Clicks on LBP Launch
3. Admin Fills out the form.
4. Clicks on Submit
5. Transaction Request Sent to PrimeDAO’s Gnosis Safe.
6. PrimeDAO confirms the transaction.
7. Admin is notified.
8. Admin comes to Prime Launch Admin Panel.
9. Transfers required amount to the LBPWrapper.
10. Clicks on FundPool/Add Liquidity and adds liquidity to LBP. BPT/Pool Tokens   are help by LBPWrapper until end time.
11. After adding liquidity, Launch is Live.
12. After end time, Admin comes to Admin Dashboard.
13. Clicks on Remove Liquidity to gets back funding and project tokens back.
   Launch ended.
Note:- Smart contract will provide functionality to retrieve pool tokens but, it won't be available on the UI.

Specification:-
Smart Contract Specification:-
- Admin should not be able to access all the owner functionality provided by   LBP. Check functionality here.
- LBP should be wrapped using LBPWrapper. LBPWrapper will be LBP’s owner.
- One LBPWrapper for one LBP and vice-e-versa.
- LBPWrapper will hold the BPT/Pool tokens until the endtime is reached.
- LBPWrapper is directly owned by Admin.
- LBPWrapperFactory is responsible for creating LBPWrapper. This functionality can  only be called  Safe.
- LBPWrapperFactory should be owned by Safe.
- Swap Fee is 1% for all pool.
- Liquidity will be added by the admin after creation process.
- The liquidity that is going to be added should be the same that is confirmed by  PrimeDAO’s Gnosis Safe.
- Weights cannot be updated after the creation process.
- PrimeDAO fee will be charged upfront that is after creation process when Admin invokes `fundPool` function. Note: Admin will have to send Project tokens accordingly.

Creation Process:-
- Admin will send a transaction request to Safe.
- Once confirmed by Safe, it should execute the following things at once,
 1. Create LBP (LBPFactory.create())
 2. Update Weights (LBP.updateWeightsGradually())

Adding Liquidity:-
- Admin will add liquidity after the creation process. Liquidity can only be added once.
- PrimeDAO fee is collected at this point. Upfront.
- Admin transfers Project tokens and funding tokens to LBPWrapper.
- Admin invokes method `fundPool` and this method adds liquidity to LBP.

Admin Interaction:-
It is limited. Here are the functions available with the admin.
- Add Liquidity (only once after the creation process).
- LBP.setSwapEnabled()
- Admin can exitPool using LBPWrapper after endTime only.
- Admin can retrieve pool tokens (only in smart contract, not used in UI)
- Admin can retrieve project tokens and funding tokens (only if fundPool fails) (They cannot retrieve them during the Launch is live. Only before adding liquidity or after endtime)

What Admin is not allowed to do:-
- Update weights after the creation process.
- Change swap fee.
- Add liquidity more than once.
- Retrieve project tokens and funding tokens after liquidity is added and before endtime.

User Interaction:-
Users are only limited to swapping.

**Comment by dkent600** [comment]
@BartuCulha Why was this closed?  We do need this.

**Comment by renc-curvelabs** [comment]
Hey @BartuCulha - we do not need a mock for this, we will just use the same design from LBP

**Comment by BartuCulha** [comment]
got it thanks @renc-curvelabs

**Comment by dkent600** [comment]
this is a dup of #187
