### ISSUE TITLE
Request Information URL won't work

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#737]
Request Information Button on the homepage and Register page won't work. 

Where should we navigate the user? @blink-km 

Register Page:
https://ethereum-staging-launch-prime.vercel.app/register

Broken link:
https://www.typeform.com/private-typeform/?utm_source=typeform.com-18871874-free&utm_medium=typeform&utm_content=typeform-private&utm_campaign=xwkxA9XP

**Comment by blink-km** [comment]
Our Typeform payments didn't go through, so our Typeform temporarily went down

**Comment by blink-km** [comment]
This is resolved
