### ISSUE TITLE
Support Button needs new URL

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#738]
We need a new url for the support button current one goes here:
https://www.typeform.com/explore/?utm_source=typeform.com&utm_medium=typeform&utm_content=typeform-incorrectURL&utm_campaign=viral_expt

![Register-Prime-Launch (1).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/9d8eea72-25ac-4651-87dc-8fc5b5722962)

**Comment by blink-km** [comment]
Fixed
