### ISSUE TITLE
Import file name capitalization is wrong

### ISSUE THREAD

**Issue by giladt** [PrimeDAO/prime-launch-dapp#76]
import { NumberService } from "services/**N**umberService";
import { DialogService } from "./**D**ialogService";

**Comment by dkent600** [comment]
I don't see a problem with dialogService (all are correctly DialogService), I do see numberService should be NumberService.

**Comment by dkent600** [comment]
Fixed the cases of numberService

**Comment by dkent600** [comment]
Actually I found dialogService and fixed
