### ISSUE TITLE
Unable to create a seed: Sorry, an error occurred: Error: Request failed with status code 403

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#767]
### Steps to reproduce:
Navigate here: https://prime-launch-dev.vercel.app/newSeed/
Begin the fill out the registration form
Go to the last page
Click Submit

### Currently:
After clicking Submit button UI throws this error message: Sorry, an error occurred: Error: Request failed with status code 403
I was unable to submit the seed.

### Console log:
Failed to load resource: the server responded with a status of 403 ()
aurelia-logging-console.js?dc89:45 ERROR [Prime Launch] Sorry, an error occurred
Error: Error: Request failed with status code 403
    at PinataIpfsClient.addAndPinData (webpack-internal:///e+5z:45:19)
    at async SeedService.deploySeed (webpack-internal:///o9kq:139:30)
    at async Stage7.submit (webpack-internal:///newLaunch/seed/stages/stage7:56:43)

### Expected:
To be able to submit the seed

**Comment by hiaux0** [comment]
Fixed by updating Pinata keys on vercel
