### ISSUE TITLE
Set overflow-x for `launchGrid` and `seedSummary` to auto

### ISSUE THREAD

**Issue by giladt** [PrimeDAO/prime-launch-dapp#77]
![image](https://user-images.githubusercontent.com/2517870/122821421-1cef9200-d2dd-11eb-800f-62d2e6a726b2.png)

Setting `overflow-x: auto;` will fix the width of the page to screen size and enable horizontal scroll to the launches list.
The same goes for seedSummary, in the case where the value is extremely long.

**Comment by dkent600** [comment]
I am working on this page now,  it has a different layout for mobile.  I'll send you the wireframe.  So I'll close this .  Thanks!
