### ISSUE TITLE
Cannot see SEED in Admin Dashboard

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-launch-dapp#782]
Steps to reproduce: 
1. Navigate here:
2. Connect wallet: 0xE834627cDE2dC8F55Fe4a26741D3e91527A8a498
3. Find the seed:  "Bartu's Test"
4. Click on it
5. click on the dropdown inside the admin dashboard

Result:
Not able to see "Bartu's test" in the dropdown

Expected:
To see "Bartu's test" 
Contract creator address can be seen here:
https://rinkeby.etherscan.io/address/0xE7de74D2C7CB5E263B77eADbE760B3Df549b6f9C

**Comment by testing-life** [comment]
there is a mismatch between default address and admin address in this specific seed.
![image](https://user-images.githubusercontent.com/85691163/189593440-57e4a8a1-a1b9-4f6c-9ea6-ede7cc614abd.png)
this line 
```
      this.seeds = this.seedService.seedsArray
        .filter((seed) => { return seed.admin.toLowerCase() === defaultAccount;});
```
filters out seeds which addresses don't match the default address

**Comment by BartuCulha** [comment]
Cannot repro
